#! /usr/bin/env bash
#
# Installation script for the kiosk software
# Runs directly on the kiosk machine in the home directory of the user
# that will run the kiosk
#

BROWSER=$1

case $BROWSER in
    midori)
        ;;
    chromium)
        ;;
    *)
	echo "unknown browser $BROWSER - using chromium"
	BROWSER="chromium"
	;;
esac
    
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox -y
sudo apt-get install xdotool -y
sudo apt-get install iptables -y

case $BROWSER in
     midori)
         sudo apt-get install --no-install-recommends midori -y
	 ;;
     chromium)
	 sudo apt-get install --no-install-recommends chromium-browser -y
	;;
esac

# Python requirements
sudo apt-get install python3 python3-bcrypt -y
#
# *******
# there is currently (AFAICT) no apt package for the 'multipart' python library (https://pypi.org/project/multipart/)
# although, confusingly, there is a 'python3-multipart' which is a totally different package
# to work around this, install multipart using pip, bypassing the complaints about virtual environments etc.
# I suppose I should package the 'kiosk' program as a pyinstaller built executable to avoid this issue
# ********
#
sudo apt install python3-pip -y
pip install multipart --break-system-packages

#
# Start off in home directory
#
cd
KIOSK_DIR=`pwd`/kiosk
(
    cd $KIOSK_DIR

    # Set the password for the kiosk browser page
    ./kiosk_pw.py
    echo $BROWSER > $KIOSK_DIR/.kiosk_browser
)

cat > openbox-autostart <<EOF
# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms

# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp

cd $KIOSK_DIR
# the following command rebinds port 80 to 8000 so the script is not required
# to run as root
sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000

#
# loop running the kiosk script
#
while true; do
  ./kiosk.py
done
EOF

sudo cp openbox-autostart /etc/xdg/openbox/autostart

cat > .profile << EOF
[[ -z "\$DISPLAY" && "\$XDG_VTNR" -eq 1 ]] && startx -- -nocursor
EOF

cat > keyF5 <<EOF
export DISPLAY=":0"
xdotool key F5
exit
EOF
chmod +x keyF5

echo "Remember to use raspi-config to set automatic CLI login"


