#! /usr/bin/env bash
#
# Installation script for the kiosk software
# Runs directly on the kiosk machine in the home directory of the user
# that will run the kiosk
#

BROWSER=$1

#
# Test whether we are running on raspian or armbian
ARMBIAN=`which armbian-config`

if [ ! -z "$ARMBIAN" ] ; then
    echo "Installing for Armbian"
else
    echo "Installing for Raspberry Pi"
fi

case $BROWSER in
    midori)
        ;;
    chromium)
        ;;
    *)
	echo "unknown browser $BROWSER - using chromium"
	BROWSER="chromium"
	;;
esac
    
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox -y
sudo apt-get install xdotool -y
sudo apt-get install iptables -y

case $BROWSER in
     midori)
	BROWSER_PACKAGE="midori"
	 ;;
     chromium)
	if [ ! -z "$ARMBIAN" ]; then
	    BROWSER_PACKAGE="chromium"
	else
	    BROWSER_PACKAGE="chromium-browser"
	fi
	;;
esac
sudo apt-get install --no-install-recommends $BROWSER_PACKAGE -y

# Python requirements
sudo apt-get install python3 python3-bcrypt -y
#
# *******
# there is currently (AFAICT) no apt package for the 'multipart' python library (https://pypi.org/project/multipart/)
# although, confusingly, there is a 'python3-multipart' which is a totally different package
# to work around this, install multipart using pip, bypassing the complaints about virtual environments etc.
# I suppose I should package the 'kiosk' program as a pyinstaller built executable to avoid this issue
# ********
#
sudo apt install python3-pip -y
pip install multipart --break-system-packages

#
# Start off in home directory
#
cd
KIOSK_DIR=`pwd`/kiosk
(
    cd $KIOSK_DIR

    # Set the password for the kiosk browser page
    ./kiosk_pw.py
    echo $BROWSER > $KIOSK_DIR/.kiosk_browser
)

cat > openbox-autostart <<EOF
# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms

# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp

cd $KIOSK_DIR
# the following command rebinds port 80 to 8000 so the script is not required
# to run as root
sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000

#
# loop running the kiosk script
#
while true; do
  #
  # Workaround: chromium browser has a tendency to fill the disk with temporary files
  #
  rm -rf ~/.config/chromium

  ./kiosk.py
done
EOF

sudo cp openbox-autostart /etc/xdg/openbox/autostart

cat > .profile << EOF
[[ -z "\$DISPLAY" && "\$XDG_VTNR" -eq 1 ]] && startx -- -nocursor
EOF

cat > keyF5 <<EOF
export DISPLAY=":0"
xdotool key F5
exit
EOF
chmod +x keyF5

if [ ! -z "$ARMBIAN" ]; then
    echo "Setting up Armbian auto login
    # there is currently no equivalent under Armbian to setting up login through raspi-config, and 
    # the process is poorly documented
    sudo mkdir -p /etc/systemd/system/getty@tty1.service.d/
    WHOAMI=`whoami`
    cat > autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin $WHOAMI %I $TERM
EOF
    sudo mv autologin.conf mkdir /etc/systemd/system/getty@tty1.service.d/
    #
    # also, make sure user can run sudo w/o a password
    #
    cat > sudo_$WHOAMI << EOF
$WHOAMI ALL=(ALL) NOPASSWD:ALL
EOF
    sudo mv sudo_$WHOAMI /etc/sudoers.d
else
    echo "Remember to use raspi-config to set automatic CLI login"
fi



